### ISSUE TITLE
What settings are required to run the TransiEnt library properly？

### ISSUE THREAD

**Issue by Cong-boy** [TransiEnt-official/transient-lib#4]
When running test cases for the TransiEnt library, Dymola often suggests that certain files cannot be found.
For example,
>>  Looking for file: ADD_YOUR_PATH_TO_TRANSIENT_HERE/TransiEnt2.0.1/Tables//ambient/UndergroundTemperature_Duesseldorf_1m_2017.txt
 
>> Calling File: F:/Modelica Library/transient-2.0.1-master/ADD_YOUR_PATH_TO_TRANSIENT_HERE/TransiEnt2.0.1/Tables/ambient/UndergroundTemperature_Duesseldorf_1m_2017.txt

>> Looking for file: ADD_YOUR_PATH_TO_TRANSIENT_HERE/TransiEnt2.0.1/Tables/electricity/ElectricityPrices_DayAhead_EPEX_Spot_2011.txt

>> Calling File: F:/Modelica Library/transient-2.0.1-master/ADD_YOUR_PATH_TO_TRANSIENT_HERE/TransiEnt2.0.1/Tables/electricity/ElectricityPrices_DayAhead_EPEX_Spot_2011.txt

![image](https://user-images.githubusercontent.com/75715006/169656879-c1538126-1b6a-471b-9ff8-9476fa3d59c3.png)
![image](https://user-images.githubusercontent.com/75715006/169657419-2e7a995b-d22d-4286-ace3-a65dbc861d4a.png)

**Comment by maggi94** [comment]
Hello Cong-boy,
sorry for being so late in replying. When you download the zip file of our version 2.0.2 (found in Releases), you have to customize the script loadTransiEnt.mos like it is written in the Readme File. Afterwards it should work.
With kind regards

Markus
