### ISSUE TITLE
remove version number in folder name

### ISSUE THREAD

**Issue by sebglom** [TransiEnt-official/transient-lib#6]
In a recent commit, the version number has been specified at the top-level folder as "TransiEnt 2.0.2-dev". It should be considered to keep the file system consistent across different version numbers. Changing file paths in the future could break some code.

Instead of specifying version numbers in the file system, release tags or the ReadMe file can be used for version specification.

**Comment by maggi94** [comment]
Thank you sebglom for your feedback. You are right. I will consider it!
